export const GLOSSARY: Record<string, string> = {
  'hPa': 'Hectopascals — the unit used to measure barometric pressure. Standard sea-level pressure is ~1013 hPa. Fish are sensitive to changes in this number.',
  'barometric pressure': 'The weight of the atmosphere pressing down. Fish have swim bladders that sense pressure changes, which triggers or suppresses feeding behavior.',
  'pressure trend': 'Whether barometric pressure is rising, falling, or stable over the last few hours. Falling pressure generally triggers feeding; rising pressure after a front often slows it.',
  'thermocline': 'A distinct layer in a lake where water temperature drops sharply. Fish often suspend just above it where oxygen and temperature are ideal.',
  'lee side': 'The side of a structure or shoreline sheltered from the wind. Baitfish get blown to the windward shore, so predators often stack on the downwind (lee) side.',
  'leeward': 'The sheltered side, away from the direction the wind is blowing. Often holds concentrations of baitfish pushed by wind.',
  'windward': 'The side directly facing the wind. Wind pushes baitfish and surface disturbance to this shore, drawing predators.',
  'structure': 'Any underwater feature that changes the bottom contour — points, humps, ledges, drop-offs, brush piles. Fish use structure as ambush points and navigational highways.',
  'drop-off': 'A sudden change in depth — where shallow water quickly transitions to deep. A prime ambush zone for predator fish.',
  'ledge': 'An underwater shelf or step-down in depth. Fish use ledges as staging areas, especially in summer and winter.',
  'lake turnover': 'A seasonal mixing event where surface and deep water swap layers. Disrupts oxygen levels and temporarily scatters fish until the lake stabilizes.',
  'cold front': 'A mass of cold air moving in, usually bringing wind, dropping pressure followed by rising pressure and clear skies. The 24-48 hours before a front are often the best fishing.',
  'post-front': 'The period after a cold front passes — high pressure, blue skies, dropping temperatures. Generally the toughest fishing conditions; fish go deep and stop feeding.',
  'finesse': 'A light-tackle fishing approach using small baits, light line, and subtle presentations. Used when fish are pressured or inactive.',
  'presentation': 'How a bait is delivered and moved through the water — the combination of cast placement, depth, speed, and action.',
  'suspended': 'Fish holding in open water at a specific depth, not near the bottom or surface. Common during temperature or pressure transitions.',
  'forage': 'The baitfish and prey species that gamefish feed on — shad, alewife, shiners, crayfish, perch. Matching forage size and color is key.',
  'spawn': 'The fish reproductive period when they move shallow to lay eggs. Pre-spawn fish feed aggressively; actively spawning fish are often uncatchable.',
  'pre-spawn': 'The period just before spawning when fish feed heavily to build energy. Often the most aggressive and catchable window of the year.',
  'Carolina rig': 'A bottom fishing rig with a sliding weight on the main line, a swivel, and a leader with a soft plastic bait. Covers bottom efficiently.',
  'dropshot': 'A finesse rig where the hook is tied above a bottom weight, suspending the bait just off the bottom. Deadly for inactive fish.',
  'bottom bouncer': 'A weighted wire rig that drags along the bottom while trolling, keeping live bait or spinners near the floor. Classic walleye technique.',
  'downrigger': 'A mechanical device on a boat that uses a heavy cannonball weight to troll lures at precise depths. Essential for salmon and lake trout.',
  'jig': 'A weighted hook with a lead head, often tipped with soft plastic or live bait. The most versatile and widely used fishing lure.',
  'spinnerbait': 'A lure with one or more spinning metal blades that create vibration and flash. Effective in stained water and around vegetation.',
  'crankbait': 'A hard lipped lure that dives to a specific depth when retrieved. Lip size and shape determines how deep it runs.',
  'topwater': 'Lures designed to be fished on the water surface — poppers, walkers, frogs. Most effective at low light and when fish are actively chasing baitfish.',
  'swimbait': 'A soft or hard lure designed to mimic a swimming baitfish. Fished at various depths to imitate natural prey.',
  'retrieve': 'The technique used to bring a lure back to the angler — steady, stop-and-go, burn-and-kill, etc. Matching retrieve to conditions is critical.',
  'dead stick': 'A motionless presentation — letting the bait sit perfectly still, often under a float. Deadly for inactive fish in cold water.',
  'troll': 'Dragging lures or bait behind a moving boat to cover large areas of water. Standard technique for open-water species like salmon and walleye.',
  'baitfish': 'Small forage fish — shad, alewife, shiners, smelt — that larger gamefish prey on. Finding baitfish usually means finding predators nearby.',
  'weed edge': 'The outer boundary of aquatic vegetation where it transitions to open water or deeper areas. A prime ambush location for many species.',
  'rip-rap': 'Rocks placed along a shoreline or dam for erosion control. Holds crayfish and baitfish, attracting bass, walleye, and other species.',
  'point': 'A finger of land or underwater structure extending into a body of water. Fish use points as ambush locations and migration highways.',
}
